# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bWexJSaRZlj9jyHEniUHjRojqQ8PdBTA
"""

#1.Importing necessary libraries
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

#2.Loading Iris dataset
iris=load_iris()
x=iris.data     # Input Data
y=iris.target   #Output Label

#3.Splitting the data Train - 80%, Test - 20%
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

#4.Assigining K values
for k in [1,3,5,7,9]:

#5.Training model with dfferent k values

  knn=KNeighborsClassifier(n_neighbors=k)
  knn.fit(x_train,y_train)

#6.Predicting the output for Test dataset

  y_pred=knn.predict(x_test)

 #7.Calculating accuracy for predicted,actual data

  accuracy=accuracy_score(y_test,y_pred)

#8.Printing the accuracy for various k values

  print(f"K: {k} -> Accuracy: {accuracy:.2f}")